# fly.toml app configuration file generated for loe-vibecode on 2026-05-26T02:42:20Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'loe-vibecode'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
